// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint

import 'package:built_collection/built_collection.dart';
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart' show StandardJsonPlugin;
import 'package:ferry_exec/ferry_exec.dart';
import 'package:gql_code_builder_serializers/gql_code_builder_serializers.dart'
    show OperationSerializer;
import 'package:pulse/graphql/__generated__/schema.schema.gql.dart'
    show
        GAttachmentOwnerKind,
        GCreateChatRoomInput,
        GCreateCommentInput,
        GCreatePostInput,
        GCreateTagInput,
        GCreateTaskInput,
        GDecisionStatus,
        GDevicePlatform,
        GEditPostInput,
        GEditTaskInput,
        GGrantTagInput,
        GIssueAttachmentUploadInput,
        GJSON,
        GNotificationFilter,
        GNotificationReason,
        GNotificationUrgency,
        GPermissionBundle,
        GPostSort,
        GPostTagInput,
        GPrincipalKind,
        GPrincipalStatus,
        GSearchKind,
        GSendMessageInput,
        GSubscribeTagInput,
        GSubscriptionUrgency,
        GTagRootKind,
        GTaskStatus,
        GTaskTagInput,
        GTime;
import 'package:pulse/graphql/operations/__generated__/chat.data.gql.dart'
    show
        GChatRoomDetailData,
        GChatRoomDetailData_chatRoom,
        GChatRoomDetailData_chatRoom_messages,
        GChatRoomDetailData_chatRoom_messages_edges,
        GChatRoomDetailData_chatRoom_messages_edges_node,
        GChatRoomDetailData_chatRoom_messages_edges_node_author,
        GChatRoomDetailData_chatRoom_messages_edges_node_replyTo,
        GChatRoomDetailData_chatRoom_participants,
        GChatRoomDetailData_chatRoom_participants_principal,
        GChatRoomDetailData_chatRoom_tags,
        GChatRoomSummaryData,
        GChatRoomSummaryData_participants,
        GChatRoomSummaryData_participants_principal,
        GChatRoomSummaryData_tags,
        GCreateChatRoomData,
        GCreateChatRoomData_createChatRoom,
        GCreateChatRoomData_createChatRoom_participants,
        GCreateChatRoomData_createChatRoom_participants_principal,
        GCreateChatRoomData_createChatRoom_tags,
        GMessageAddedData,
        GMessageAddedData_messageAdded,
        GMessageAddedData_messageAdded_author,
        GMessageAddedData_messageAdded_replyTo,
        GMessageSummaryData,
        GMessageSummaryData_author,
        GMessageSummaryData_replyTo,
        GSendMessageData,
        GSendMessageData_sendMessage,
        GSendMessageData_sendMessage_author,
        GSendMessageData_sendMessage_replyTo;
import 'package:pulse/graphql/operations/__generated__/chat.req.gql.dart'
    show
        GChatRoomDetailReq,
        GChatRoomSummaryReq,
        GCreateChatRoomReq,
        GMessageAddedReq,
        GMessageSummaryReq,
        GSendMessageReq;
import 'package:pulse/graphql/operations/__generated__/chat.var.gql.dart'
    show
        GChatRoomDetailVars,
        GChatRoomSummaryVars,
        GCreateChatRoomVars,
        GMessageAddedVars,
        GMessageSummaryVars,
        GSendMessageVars;
import 'package:pulse/graphql/operations/__generated__/health.data.gql.dart'
    show GHealthData;
import 'package:pulse/graphql/operations/__generated__/health.req.gql.dart'
    show GHealthReq;
import 'package:pulse/graphql/operations/__generated__/health.var.gql.dart'
    show GHealthVars;
import 'package:pulse/graphql/operations/__generated__/impersonation.data.gql.dart'
    show
        GEndImpersonationData,
        GEndImpersonationData_endImpersonation,
        GEndImpersonationData_endImpersonation_acting,
        GEndImpersonationData_endImpersonation_effective,
        GImpersonateData,
        GImpersonateData_impersonate,
        GImpersonateData_impersonate_acting,
        GImpersonateData_impersonate_effective,
        GRegisterDeviceTokenData,
        GUnregisterDeviceTokenData,
        GViewerImpersonationStateData,
        GViewerImpersonationStateData_viewerImpersonationState,
        GViewerImpersonationStateData_viewerImpersonationState_acting,
        GViewerImpersonationStateData_viewerImpersonationState_effective;
import 'package:pulse/graphql/operations/__generated__/impersonation.req.gql.dart'
    show
        GEndImpersonationReq,
        GImpersonateReq,
        GRegisterDeviceTokenReq,
        GUnregisterDeviceTokenReq,
        GViewerImpersonationStateReq;
import 'package:pulse/graphql/operations/__generated__/impersonation.var.gql.dart'
    show
        GEndImpersonationVars,
        GImpersonateVars,
        GRegisterDeviceTokenVars,
        GUnregisterDeviceTokenVars,
        GViewerImpersonationStateVars;
import 'package:pulse/graphql/operations/__generated__/login.data.gql.dart'
    show GLoginData, GLoginData_login, GLoginData_login_viewer;
import 'package:pulse/graphql/operations/__generated__/login.req.gql.dart'
    show GLoginReq;
import 'package:pulse/graphql/operations/__generated__/login.var.gql.dart'
    show GLoginVars;
import 'package:pulse/graphql/operations/__generated__/logout.data.gql.dart'
    show GLogoutData;
import 'package:pulse/graphql/operations/__generated__/logout.req.gql.dart'
    show GLogoutReq;
import 'package:pulse/graphql/operations/__generated__/logout.var.gql.dart'
    show GLogoutVars;
import 'package:pulse/graphql/operations/__generated__/notifications.data.gql.dart'
    show
        GNotificationReceivedData_notificationReceived_source,
        GNotificationSummaryData_source,
        GNotificationsInboxData_notifications_edges_node_source,
        GMarkAllNotificationsReadData,
        GMarkNotificationReadData,
        GNotificationReceivedData,
        GNotificationReceivedData_notificationReceived,
        GNotificationReceivedData_notificationReceived_sourceTag,
        GNotificationReceivedData_notificationReceived_source__asComment,
        GNotificationReceivedData_notificationReceived_source__asMessage,
        GNotificationReceivedData_notificationReceived_source__asPost,
        GNotificationReceivedData_notificationReceived_source__asTask,
        GNotificationReceivedData_notificationReceived_source__base,
        GNotificationSummaryData,
        GNotificationSummaryData_sourceTag,
        GNotificationSummaryData_source__asComment,
        GNotificationSummaryData_source__asMessage,
        GNotificationSummaryData_source__asPost,
        GNotificationSummaryData_source__asTask,
        GNotificationSummaryData_source__base,
        GNotificationsInboxData,
        GNotificationsInboxData_notifications,
        GNotificationsInboxData_notifications_edges,
        GNotificationsInboxData_notifications_edges_node,
        GNotificationsInboxData_notifications_edges_node_sourceTag,
        GNotificationsInboxData_notifications_edges_node_source__asComment,
        GNotificationsInboxData_notifications_edges_node_source__asMessage,
        GNotificationsInboxData_notifications_edges_node_source__asPost,
        GNotificationsInboxData_notifications_edges_node_source__asTask,
        GNotificationsInboxData_notifications_edges_node_source__base;
import 'package:pulse/graphql/operations/__generated__/notifications.req.gql.dart'
    show
        GMarkAllNotificationsReadReq,
        GMarkNotificationReadReq,
        GNotificationReceivedReq,
        GNotificationSummaryReq,
        GNotificationsInboxReq;
import 'package:pulse/graphql/operations/__generated__/notifications.var.gql.dart'
    show
        GMarkAllNotificationsReadVars,
        GMarkNotificationReadVars,
        GNotificationReceivedVars,
        GNotificationSummaryVars,
        GNotificationsInboxVars;
import 'package:pulse/graphql/operations/__generated__/posts.data.gql.dart'
    show
        GCommentSummaryData,
        GCommentSummaryData_author,
        GCommentSummaryData_reactions,
        GCreateCommentData,
        GCreateCommentData_createComment,
        GCreateCommentData_createComment_author,
        GCreateCommentData_createComment_reactions,
        GCreatePostData,
        GCreatePostData_createPost,
        GCreatePostData_createPost_author,
        GCreatePostData_createPost_comments,
        GCreatePostData_createPost_comments_edges,
        GCreatePostData_createPost_comments_edges_node,
        GCreatePostData_createPost_reactions,
        GMarkPostReadData,
        GMarkPostReadData_markPostRead,
        GPostChangedData,
        GPostChangedData_postChanged,
        GPostChangedData_postChanged_author,
        GPostChangedData_postChanged_comments,
        GPostChangedData_postChanged_comments_edges,
        GPostChangedData_postChanged_comments_edges_node,
        GPostChangedData_postChanged_reactions,
        GPostDetailData,
        GPostDetailData_post,
        GPostDetailData_post_author,
        GPostDetailData_post_comments,
        GPostDetailData_post_comments_edges,
        GPostDetailData_post_comments_edges_node,
        GPostDetailData_post_comments_edges_node_author,
        GPostDetailData_post_comments_edges_node_reactions,
        GPostDetailData_post_myPermissions,
        GPostDetailData_post_reactions,
        GPostDetailData_post_tags,
        GPostDetailData_post_tags_tag,
        GPostSummaryData,
        GPostSummaryData_author,
        GPostSummaryData_comments,
        GPostSummaryData_comments_edges,
        GPostSummaryData_comments_edges_node,
        GPostSummaryData_reactions,
        GPostsForTagData,
        GPostsForTagData_tag,
        GPostsForTagData_tag_posts,
        GPostsForTagData_tag_posts_edges,
        GPostsForTagData_tag_posts_edges_node,
        GPostsForTagData_tag_posts_edges_node_author,
        GPostsForTagData_tag_posts_edges_node_comments,
        GPostsForTagData_tag_posts_edges_node_comments_edges,
        GPostsForTagData_tag_posts_edges_node_comments_edges_node,
        GPostsForTagData_tag_posts_edges_node_reactions,
        GReactToPostData,
        GReactToPostData_reactToPost,
        GReactToPostData_reactToPost_reactions,
        GUnreactToPostData,
        GUnreactToPostData_unreactToPost,
        GUnreactToPostData_unreactToPost_reactions;
import 'package:pulse/graphql/operations/__generated__/posts.req.gql.dart'
    show
        GCommentSummaryReq,
        GCreateCommentReq,
        GCreatePostReq,
        GMarkPostReadReq,
        GPostChangedReq,
        GPostDetailReq,
        GPostSummaryReq,
        GPostsForTagReq,
        GReactToPostReq,
        GUnreactToPostReq;
import 'package:pulse/graphql/operations/__generated__/posts.var.gql.dart'
    show
        GCommentSummaryVars,
        GCreateCommentVars,
        GCreatePostVars,
        GMarkPostReadVars,
        GPostChangedVars,
        GPostDetailVars,
        GPostSummaryVars,
        GPostsForTagVars,
        GReactToPostVars,
        GUnreactToPostVars;
import 'package:pulse/graphql/operations/__generated__/search.data.gql.dart'
    show
        GSearchData_search_edges_node,
        GSearchData,
        GSearchData_search,
        GSearchData_search_edges,
        GSearchData_search_edges_node__asComment,
        GSearchData_search_edges_node__asPost,
        GSearchData_search_edges_node__asPost_author,
        GSearchData_search_edges_node__base,
        GSearchTagsData,
        GSearchTagsData_searchTags,
        GSearchTagsData_searchTags_tag;
import 'package:pulse/graphql/operations/__generated__/search.req.gql.dart'
    show GSearchReq, GSearchTagsReq;
import 'package:pulse/graphql/operations/__generated__/search.var.gql.dart'
    show GSearchTagsVars, GSearchVars;
import 'package:pulse/graphql/operations/__generated__/tag_tree.data.gql.dart'
    show
        GTagChildrenData,
        GTagChildrenData_tag,
        GTagChildrenData_tag_children,
        GTagChildrenData_tag_children_children,
        GTagSummaryData,
        GTagTreeData,
        GTagTreeData_myTagRoots,
        GTagTreeData_myTagRoots_children,
        GTagTreeData_myTagRoots_children_children,
        GTagTreeData_myTagRoots_children_children_children;
import 'package:pulse/graphql/operations/__generated__/tag_tree.req.gql.dart'
    show GTagChildrenReq, GTagSummaryReq, GTagTreeReq;
import 'package:pulse/graphql/operations/__generated__/tag_tree.var.gql.dart'
    show GTagChildrenVars, GTagSummaryVars, GTagTreeVars;
import 'package:pulse/graphql/operations/__generated__/viewer.data.gql.dart'
    show GViewerData, GViewerData_viewer, GViewerData_viewer_homeTag;
import 'package:pulse/graphql/operations/__generated__/viewer.req.gql.dart'
    show GViewerReq;
import 'package:pulse/graphql/operations/__generated__/viewer.var.gql.dart'
    show GViewerVars;

part 'serializers.gql.g.dart';

final SerializersBuilder _serializersBuilder = _$serializers.toBuilder()
  ..add(OperationSerializer())
  ..add(GNotificationReceivedData_notificationReceived_source.serializer)
  ..add(GNotificationSummaryData_source.serializer)
  ..add(GNotificationsInboxData_notifications_edges_node_source.serializer)
  ..add(GSearchData_search_edges_node.serializer)
  ..addPlugin(StandardJsonPlugin());
@SerializersFor([
  GAttachmentOwnerKind,
  GChatRoomDetailData,
  GChatRoomDetailData_chatRoom,
  GChatRoomDetailData_chatRoom_messages,
  GChatRoomDetailData_chatRoom_messages_edges,
  GChatRoomDetailData_chatRoom_messages_edges_node,
  GChatRoomDetailData_chatRoom_messages_edges_node_author,
  GChatRoomDetailData_chatRoom_messages_edges_node_replyTo,
  GChatRoomDetailData_chatRoom_participants,
  GChatRoomDetailData_chatRoom_participants_principal,
  GChatRoomDetailData_chatRoom_tags,
  GChatRoomDetailReq,
  GChatRoomDetailVars,
  GChatRoomSummaryData,
  GChatRoomSummaryData_participants,
  GChatRoomSummaryData_participants_principal,
  GChatRoomSummaryData_tags,
  GChatRoomSummaryReq,
  GChatRoomSummaryVars,
  GCommentSummaryData,
  GCommentSummaryData_author,
  GCommentSummaryData_reactions,
  GCommentSummaryReq,
  GCommentSummaryVars,
  GCreateChatRoomData,
  GCreateChatRoomData_createChatRoom,
  GCreateChatRoomData_createChatRoom_participants,
  GCreateChatRoomData_createChatRoom_participants_principal,
  GCreateChatRoomData_createChatRoom_tags,
  GCreateChatRoomInput,
  GCreateChatRoomReq,
  GCreateChatRoomVars,
  GCreateCommentData,
  GCreateCommentData_createComment,
  GCreateCommentData_createComment_author,
  GCreateCommentData_createComment_reactions,
  GCreateCommentInput,
  GCreateCommentReq,
  GCreateCommentVars,
  GCreatePostData,
  GCreatePostData_createPost,
  GCreatePostData_createPost_author,
  GCreatePostData_createPost_comments,
  GCreatePostData_createPost_comments_edges,
  GCreatePostData_createPost_comments_edges_node,
  GCreatePostData_createPost_reactions,
  GCreatePostInput,
  GCreatePostReq,
  GCreatePostVars,
  GCreateTagInput,
  GCreateTaskInput,
  GDecisionStatus,
  GDevicePlatform,
  GEditPostInput,
  GEditTaskInput,
  GEndImpersonationData,
  GEndImpersonationData_endImpersonation,
  GEndImpersonationData_endImpersonation_acting,
  GEndImpersonationData_endImpersonation_effective,
  GEndImpersonationReq,
  GEndImpersonationVars,
  GGrantTagInput,
  GHealthData,
  GHealthReq,
  GHealthVars,
  GImpersonateData,
  GImpersonateData_impersonate,
  GImpersonateData_impersonate_acting,
  GImpersonateData_impersonate_effective,
  GImpersonateReq,
  GImpersonateVars,
  GIssueAttachmentUploadInput,
  GJSON,
  GLoginData,
  GLoginData_login,
  GLoginData_login_viewer,
  GLoginReq,
  GLoginVars,
  GLogoutData,
  GLogoutReq,
  GLogoutVars,
  GMarkAllNotificationsReadData,
  GMarkAllNotificationsReadReq,
  GMarkAllNotificationsReadVars,
  GMarkNotificationReadData,
  GMarkNotificationReadReq,
  GMarkNotificationReadVars,
  GMarkPostReadData,
  GMarkPostReadData_markPostRead,
  GMarkPostReadReq,
  GMarkPostReadVars,
  GMessageAddedData,
  GMessageAddedData_messageAdded,
  GMessageAddedData_messageAdded_author,
  GMessageAddedData_messageAdded_replyTo,
  GMessageAddedReq,
  GMessageAddedVars,
  GMessageSummaryData,
  GMessageSummaryData_author,
  GMessageSummaryData_replyTo,
  GMessageSummaryReq,
  GMessageSummaryVars,
  GNotificationFilter,
  GNotificationReason,
  GNotificationReceivedData,
  GNotificationReceivedData_notificationReceived,
  GNotificationReceivedData_notificationReceived_sourceTag,
  GNotificationReceivedData_notificationReceived_source__asComment,
  GNotificationReceivedData_notificationReceived_source__asMessage,
  GNotificationReceivedData_notificationReceived_source__asPost,
  GNotificationReceivedData_notificationReceived_source__asTask,
  GNotificationReceivedData_notificationReceived_source__base,
  GNotificationReceivedReq,
  GNotificationReceivedVars,
  GNotificationSummaryData,
  GNotificationSummaryData_sourceTag,
  GNotificationSummaryData_source__asComment,
  GNotificationSummaryData_source__asMessage,
  GNotificationSummaryData_source__asPost,
  GNotificationSummaryData_source__asTask,
  GNotificationSummaryData_source__base,
  GNotificationSummaryReq,
  GNotificationSummaryVars,
  GNotificationUrgency,
  GNotificationsInboxData,
  GNotificationsInboxData_notifications,
  GNotificationsInboxData_notifications_edges,
  GNotificationsInboxData_notifications_edges_node,
  GNotificationsInboxData_notifications_edges_node_sourceTag,
  GNotificationsInboxData_notifications_edges_node_source__asComment,
  GNotificationsInboxData_notifications_edges_node_source__asMessage,
  GNotificationsInboxData_notifications_edges_node_source__asPost,
  GNotificationsInboxData_notifications_edges_node_source__asTask,
  GNotificationsInboxData_notifications_edges_node_source__base,
  GNotificationsInboxReq,
  GNotificationsInboxVars,
  GPermissionBundle,
  GPostChangedData,
  GPostChangedData_postChanged,
  GPostChangedData_postChanged_author,
  GPostChangedData_postChanged_comments,
  GPostChangedData_postChanged_comments_edges,
  GPostChangedData_postChanged_comments_edges_node,
  GPostChangedData_postChanged_reactions,
  GPostChangedReq,
  GPostChangedVars,
  GPostDetailData,
  GPostDetailData_post,
  GPostDetailData_post_author,
  GPostDetailData_post_comments,
  GPostDetailData_post_comments_edges,
  GPostDetailData_post_comments_edges_node,
  GPostDetailData_post_comments_edges_node_author,
  GPostDetailData_post_comments_edges_node_reactions,
  GPostDetailData_post_myPermissions,
  GPostDetailData_post_reactions,
  GPostDetailData_post_tags,
  GPostDetailData_post_tags_tag,
  GPostDetailReq,
  GPostDetailVars,
  GPostSort,
  GPostSummaryData,
  GPostSummaryData_author,
  GPostSummaryData_comments,
  GPostSummaryData_comments_edges,
  GPostSummaryData_comments_edges_node,
  GPostSummaryData_reactions,
  GPostSummaryReq,
  GPostSummaryVars,
  GPostTagInput,
  GPostsForTagData,
  GPostsForTagData_tag,
  GPostsForTagData_tag_posts,
  GPostsForTagData_tag_posts_edges,
  GPostsForTagData_tag_posts_edges_node,
  GPostsForTagData_tag_posts_edges_node_author,
  GPostsForTagData_tag_posts_edges_node_comments,
  GPostsForTagData_tag_posts_edges_node_comments_edges,
  GPostsForTagData_tag_posts_edges_node_comments_edges_node,
  GPostsForTagData_tag_posts_edges_node_reactions,
  GPostsForTagReq,
  GPostsForTagVars,
  GPrincipalKind,
  GPrincipalStatus,
  GReactToPostData,
  GReactToPostData_reactToPost,
  GReactToPostData_reactToPost_reactions,
  GReactToPostReq,
  GReactToPostVars,
  GRegisterDeviceTokenData,
  GRegisterDeviceTokenReq,
  GRegisterDeviceTokenVars,
  GSearchData,
  GSearchData_search,
  GSearchData_search_edges,
  GSearchData_search_edges_node__asComment,
  GSearchData_search_edges_node__asPost,
  GSearchData_search_edges_node__asPost_author,
  GSearchData_search_edges_node__base,
  GSearchKind,
  GSearchReq,
  GSearchTagsData,
  GSearchTagsData_searchTags,
  GSearchTagsData_searchTags_tag,
  GSearchTagsReq,
  GSearchTagsVars,
  GSearchVars,
  GSendMessageData,
  GSendMessageData_sendMessage,
  GSendMessageData_sendMessage_author,
  GSendMessageData_sendMessage_replyTo,
  GSendMessageInput,
  GSendMessageReq,
  GSendMessageVars,
  GSubscribeTagInput,
  GSubscriptionUrgency,
  GTagChildrenData,
  GTagChildrenData_tag,
  GTagChildrenData_tag_children,
  GTagChildrenData_tag_children_children,
  GTagChildrenReq,
  GTagChildrenVars,
  GTagRootKind,
  GTagSummaryData,
  GTagSummaryReq,
  GTagSummaryVars,
  GTagTreeData,
  GTagTreeData_myTagRoots,
  GTagTreeData_myTagRoots_children,
  GTagTreeData_myTagRoots_children_children,
  GTagTreeData_myTagRoots_children_children_children,
  GTagTreeReq,
  GTagTreeVars,
  GTaskStatus,
  GTaskTagInput,
  GTime,
  GUnreactToPostData,
  GUnreactToPostData_unreactToPost,
  GUnreactToPostData_unreactToPost_reactions,
  GUnreactToPostReq,
  GUnreactToPostVars,
  GUnregisterDeviceTokenData,
  GUnregisterDeviceTokenReq,
  GUnregisterDeviceTokenVars,
  GViewerData,
  GViewerData_viewer,
  GViewerData_viewer_homeTag,
  GViewerImpersonationStateData,
  GViewerImpersonationStateData_viewerImpersonationState,
  GViewerImpersonationStateData_viewerImpersonationState_acting,
  GViewerImpersonationStateData_viewerImpersonationState_effective,
  GViewerImpersonationStateReq,
  GViewerImpersonationStateVars,
  GViewerReq,
  GViewerVars,
])
final Serializers serializers = _serializersBuilder.build();
