package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/bcnelson/pulse/services/api/internal/audit"
	"github.com/bcnelson/pulse/services/api/internal/auth"
	"github.com/bcnelson/pulse/services/api/internal/chat"
	"github.com/bcnelson/pulse/services/api/internal/comment"
	"github.com/bcnelson/pulse/services/api/internal/graphql/model"
	"github.com/bcnelson/pulse/services/api/internal/perm"
	"github.com/bcnelson/pulse/services/api/internal/post"
	"github.com/bcnelson/pulse/services/api/internal/realtime"
	"github.com/bcnelson/pulse/services/api/internal/search"
	"github.com/bcnelson/pulse/services/api/internal/tag"
	"github.com/bcnelson/pulse/services/api/internal/task"
	"github.com/google/uuid"
)

// Messages is the resolver for the messages field.
func (r *chatRoomResolver) Messages(ctx context.Context, obj *model.ChatRoom, first *int) (*model.MessageConnection, error) {
	rid, err := uuid.Parse(obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid room id: %w", err)
	}
	limit := 100
	if first != nil && *first > 0 && *first <= 500 {
		limit = *first
	}
	return r.loadMessageConnection(ctx, rid, limit)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.LoginPayload, error) {
	userAgent := ""
	issued, principalID, err := r.Auth.Login(ctx, email, password, userAgent)
	if err != nil {
		if errors.Is(err, auth.ErrInvalidCredentials) {
			return nil, fmt.Errorf("invalid credentials")
		}
		return nil, err
	}
	user, err := r.loadUser(ctx, principalID)
	if err != nil {
		return nil, err
	}
	return &model.LoginPayload{
		Token:     issued.Token,
		ExpiresAt: issued.ExpiresAt,
		Viewer:    user,
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	// Token cannot be retrieved from ctx in M1 (we only stash Identity).
	// For now Logout requires the bearer to be present in context as a
	// stash; see TODO in middleware. Returning true unconditionally so the
	// client can drop its token even if server-side revocation is deferred.
	// M5 will tighten this once impersonation/elevated-session columns land.
	identity := auth.FromContext(ctx)
	if identity.IsAnonymous() {
		return false, nil
	}
	if token, ok := tokenFromContext(ctx); ok {
		if err := r.Auth.Logout(ctx, token); err != nil {
			return false, err
		}
	}
	return true, nil
}

// CreateTag is the resolver for the createTag field.
func (r *mutationResolver) CreateTag(ctx context.Context, input model.CreateTagInput) (*model.Tag, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	parentID, err := uuid.Parse(input.ParentID)
	if err != nil {
		return nil, fmt.Errorf("invalid parentId: %w", err)
	}
	// Authorization: must contribute on the parent.
	can, err := r.Perm.Can(ctx, identity.EffectiveID, perm.ActionContribute, parentID)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	defaults, err := jsonOrEmpty(input.Defaults)
	if err != nil {
		return nil, err
	}

	id, err := r.Tags.Create(ctx, tag.CreateInput{
		ParentID:    &parentID,
		Slug:        input.Slug,
		DisplayName: input.DisplayName,
		RootKind:    tag.RootKindOrg,
		Defaults:    defaults,
	})
	if err != nil {
		return nil, err
	}

	if err := r.Audit.Write(ctx, audit.Event{
		Action:     "tag.create",
		TargetType: "tag",
		TargetID:   id,
		Diff:       json.RawMessage(fmt.Sprintf(`{"parent_id":"%s","slug":%q}`, parentID, input.Slug)),
	}); err != nil {
		return nil, err
	}
	return r.loadTag(ctx, id)
}

// MoveTag is the resolver for the moveTag field.
func (r *mutationResolver) MoveTag(ctx context.Context, tagID string, newParentID string, reason *string) (*model.Tag, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	src, err := uuid.Parse(tagID)
	if err != nil {
		return nil, fmt.Errorf("invalid tagId: %w", err)
	}
	dst, err := uuid.Parse(newParentID)
	if err != nil {
		return nil, fmt.Errorf("invalid newParentId: %w", err)
	}

	// Per architecture Q1: authority check on both source and destination.
	canSrc, err := r.Perm.Can(ctx, identity.EffectiveID, perm.ActionOwn, src)
	if err != nil {
		return nil, err
	}
	canDst, err := r.Perm.Can(ctx, identity.EffectiveID, perm.ActionOwn, dst)
	if err != nil {
		return nil, err
	}
	if !canSrc || !canDst {
		return nil, errPermissionDenied
	}

	// TODO(M4): for large subtree*principals products, enqueue a permission-diff job
	// instead of computing inline. M1 always inlines; we accept the latency budget
	// for tags below the architecture's stated comfort threshold.
	gained, lost, err := r.computePermissionDiff(ctx, src, dst)
	if err != nil {
		return nil, err
	}
	if err := r.Tags.Move(ctx, src, dst); err != nil {
		return nil, err
	}
	diff, _ := json.Marshal(map[string]any{
		"gained": gained,
		"lost":   lost,
	})
	reasonStr := ""
	if reason != nil {
		reasonStr = *reason
	}
	if err := r.Audit.Write(ctx, audit.Event{
		Action:     "tag.move",
		TargetType: "tag",
		TargetID:   src,
		Diff:       diff,
		Reason:     reasonStr,
	}); err != nil {
		return nil, err
	}
	notifyPayload := json.RawMessage(fmt.Sprintf(
		`{"kind":"moved","tag_id":"%s","new_parent_id":"%s"}`, src, dst))
	notifySQL, notifyArgs := realtime.NotifySQL("tag."+src.String()+".structure", notifyPayload)
	if _, err := r.DB.Exec(ctx, notifySQL, notifyArgs...); err != nil {
		return nil, err
	}
	return r.loadTag(ctx, src)
}

// ArchiveTag is the resolver for the archiveTag field.
func (r *mutationResolver) ArchiveTag(ctx context.Context, tagID string) (*model.Tag, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	id, err := uuid.Parse(tagID)
	if err != nil {
		return nil, fmt.Errorf("invalid tagId: %w", err)
	}
	can, err := r.Perm.Can(ctx, identity.EffectiveID, perm.ActionOwn, id)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	if err := r.Tags.Archive(ctx, id); err != nil {
		return nil, err
	}
	if err := r.Audit.Write(ctx, audit.Event{
		Action:     "tag.archive",
		TargetType: "tag",
		TargetID:   id,
	}); err != nil {
		return nil, err
	}
	return r.loadTag(ctx, id)
}

// GrantTag is the resolver for the grantTag field.
func (r *mutationResolver) GrantTag(ctx context.Context, input model.GrantTagInput) (*model.Tag, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	tagID, err := uuid.Parse(input.TagID)
	if err != nil {
		return nil, fmt.Errorf("invalid tagId: %w", err)
	}
	principalID, err := uuid.Parse(input.PrincipalID)
	if err != nil {
		return nil, fmt.Errorf("invalid principalId: %w", err)
	}
	// Granting on a tag requires moderate-or-better on that tag.
	can, err := r.Perm.Can(ctx, identity.EffectiveID, perm.ActionModerate, tagID)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	cascade := true
	if input.Cascade != nil {
		cascade = *input.Cascade
	}
	extras := input.Extras
	if extras == nil {
		extras = []string{}
	}
	bundleDB := mapBundleGQLToDB(input.Bundle)
	_, err = r.DB.Exec(ctx, `
        INSERT INTO tag_grants (tag_id, principal_id, bundle, extra_perms, cascade, granted_by)
        VALUES ($1, $2, $3, $4, $5, $6)
        ON CONFLICT (tag_id, principal_id) DO UPDATE
            SET bundle = EXCLUDED.bundle,
                extra_perms = EXCLUDED.extra_perms,
                cascade = EXCLUDED.cascade,
                granted_by = EXCLUDED.granted_by
    `, tagID, principalID, string(bundleDB), extras, cascade, identity.EffectiveID)
	if err != nil {
		return nil, err
	}
	if err := r.Audit.Write(ctx, audit.Event{
		Action:     "tag.grant",
		TargetType: "tag",
		TargetID:   tagID,
		Diff:       json.RawMessage(fmt.Sprintf(`{"principal_id":"%s","bundle":%q,"cascade":%t}`, principalID, bundleDB, cascade)),
	}); err != nil {
		return nil, err
	}
	return r.loadTag(ctx, tagID)
}

// RevokeTagGrant is the resolver for the revokeTagGrant field.
func (r *mutationResolver) RevokeTagGrant(ctx context.Context, tagID string, principalID string) (*model.Tag, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	tID, err := uuid.Parse(tagID)
	if err != nil {
		return nil, fmt.Errorf("invalid tagId: %w", err)
	}
	pID, err := uuid.Parse(principalID)
	if err != nil {
		return nil, fmt.Errorf("invalid principalId: %w", err)
	}
	can, err := r.Perm.Can(ctx, identity.EffectiveID, perm.ActionModerate, tID)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	if _, err := r.DB.Exec(ctx,
		`DELETE FROM tag_grants WHERE tag_id = $1 AND principal_id = $2`, tID, pID); err != nil {
		return nil, err
	}
	if err := r.Audit.Write(ctx, audit.Event{
		Action:     "tag.revoke",
		TargetType: "tag",
		TargetID:   tID,
		Diff:       json.RawMessage(fmt.Sprintf(`{"principal_id":"%s"}`, pID)),
	}); err != nil {
		return nil, err
	}
	return r.loadTag(ctx, tID)
}

// SubscribeTag is the resolver for the subscribeTag field.
func (r *mutationResolver) SubscribeTag(ctx context.Context, input model.SubscribeTagInput) (*model.TagSubscription, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	tagID, err := uuid.Parse(input.TagID)
	if err != nil {
		return nil, fmt.Errorf("invalid tagId: %w", err)
	}
	can, err := r.Perm.Can(ctx, identity.EffectiveID, perm.ActionView, tagID)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	cascade := true
	if input.Cascade != nil {
		cascade = *input.Cascade
	}
	urgency := model.SubscriptionUrgencyNormal
	if input.Urgency != nil {
		urgency = *input.Urgency
	}
	reasonFilter := input.ReasonFilter
	if reasonFilter == nil {
		reasonFilter = []string{}
	}
	urgDB := mapUrgencyGQLToDB(urgency)
	if _, err := r.DB.Exec(ctx, `
        INSERT INTO subscriptions (principal_id, tag_id, cascade, urgency, reason_filter)
        VALUES ($1, $2, $3, $4, $5)
        ON CONFLICT (principal_id, tag_id) DO UPDATE
            SET cascade = EXCLUDED.cascade,
                urgency = EXCLUDED.urgency,
                reason_filter = EXCLUDED.reason_filter
    `, identity.EffectiveID, tagID, cascade, urgDB, reasonFilter); err != nil {
		return nil, err
	}
	return &model.TagSubscription{
		Cascade:      cascade,
		Urgency:      urgency,
		ReasonFilter: reasonFilter,
	}, nil
}

// UnsubscribeTag is the resolver for the unsubscribeTag field.
func (r *mutationResolver) UnsubscribeTag(ctx context.Context, tagID string) (bool, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return false, err
	}
	tID, err := uuid.Parse(tagID)
	if err != nil {
		return false, fmt.Errorf("invalid tagId: %w", err)
	}
	if _, err := r.DB.Exec(ctx,
		`DELETE FROM subscriptions WHERE principal_id = $1 AND tag_id = $2`,
		identity.EffectiveID, tID); err != nil {
		return false, err
	}
	return true, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	if len(input.Tags) == 0 {
		return nil, fmt.Errorf("at least one tag required")
	}
	tagAttachments := make([]post.TagAttachment, 0, len(input.Tags))
	for _, t := range input.Tags {
		tagID, err := uuid.Parse(t.TagID)
		if err != nil {
			return nil, fmt.Errorf("invalid tagId: %w", err)
		}
		// Authorization: must be allowed to contribute on each attached tag.
		can, err := r.Perm.Can(ctx, identity.EffectiveID, perm.ActionContribute, tagID)
		if err != nil {
			return nil, err
		}
		if !can {
			return nil, errPermissionDenied
		}
		ta := post.TagAttachment{
			TagID:        tagID,
			ViewRole:     boolOrTrue(t.ViewRole),
			InteractRole: boolOrTrue(t.InteractRole),
			ModerateRole: boolOrTrue(t.ModerateRole),
		}
		tagAttachments = append(tagAttachments, ta)
	}
	mentions, err := r.resolveMentionSlugs(ctx, post.ExtractMentionSlugs(input.Body))
	if err != nil {
		return nil, err
	}
	id, err := r.Posts.Create(ctx, post.CreateInput{
		AuthorID: identity.EffectiveID,
		Title:    input.Title,
		Body:     input.Body,
		Tags:     tagAttachments,
		Mentions: mentions,
	})
	if err != nil {
		return nil, err
	}
	if err := r.Audit.Write(ctx, audit.Event{
		Action: "post.create", TargetType: "post", TargetID: id,
	}); err != nil {
		return nil, err
	}
	return r.loadPost(ctx, id)
}

// EditPost is the resolver for the editPost field.
func (r *mutationResolver) EditPost(ctx context.Context, input model.EditPostInput) (*model.Post, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	id, err := uuid.Parse(input.PostID)
	if err != nil {
		return nil, fmt.Errorf("invalid postId: %w", err)
	}
	can, err := r.Perm.CanOnPost(ctx, identity.EffectiveID, perm.ActionContribute, id)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	if err := r.Posts.Edit(ctx, id, identity.EffectiveID, input.Title, input.Body); err != nil {
		if errors.Is(err, post.ErrAlreadyEdited) {
			return r.loadPost(ctx, id)
		}
		return nil, err
	}
	if err := r.Audit.Write(ctx, audit.Event{
		Action: "post.edit", TargetType: "post", TargetID: id,
	}); err != nil {
		return nil, err
	}
	return r.loadPost(ctx, id)
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, postID string) (bool, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return false, err
	}
	id, err := uuid.Parse(postID)
	if err != nil {
		return false, fmt.Errorf("invalid postId: %w", err)
	}
	can, err := r.Perm.CanOnPost(ctx, identity.EffectiveID, perm.ActionModerate, id)
	if err != nil {
		return false, err
	}
	if !can {
		return false, errPermissionDenied
	}
	if err := r.Posts.Delete(ctx, id); err != nil {
		return false, err
	}
	return true, r.Audit.Write(ctx, audit.Event{
		Action: "post.delete", TargetType: "post", TargetID: id,
	})
}

// SetDecisionStatus is the resolver for the setDecisionStatus field.
func (r *mutationResolver) SetDecisionStatus(ctx context.Context, postID string, status *model.DecisionStatus) (*model.Post, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	id, err := uuid.Parse(postID)
	if err != nil {
		return nil, fmt.Errorf("invalid postId: %w", err)
	}
	can, err := r.Perm.CanOnPost(ctx, identity.EffectiveID, perm.ActionModerate, id)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	var dbStatus *string
	if status != nil {
		s := mapDecisionGQLToDB(*status)
		dbStatus = &s
	}
	if err := r.Posts.SetDecisionStatus(ctx, id, dbStatus); err != nil {
		return nil, err
	}
	if err := r.Audit.Write(ctx, audit.Event{
		Action: "post.set_decision", TargetType: "post", TargetID: id,
	}); err != nil {
		return nil, err
	}
	return r.loadPost(ctx, id)
}

// SetDenyFlag is the resolver for the setDenyFlag field.
func (r *mutationResolver) SetDenyFlag(ctx context.Context, postID string, deny bool) (*model.Post, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	id, err := uuid.Parse(postID)
	if err != nil {
		return nil, fmt.Errorf("invalid postId: %w", err)
	}
	can, err := r.Perm.CanOnPost(ctx, identity.EffectiveID, perm.ActionModerate, id)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	if err := r.Posts.SetDenyFlag(ctx, id, deny); err != nil {
		return nil, err
	}
	if err := r.Audit.Write(ctx, audit.Event{
		Action: "post.set_deny", TargetType: "post", TargetID: id,
	}); err != nil {
		return nil, err
	}
	return r.loadPost(ctx, id)
}

// ReactToPost is the resolver for the reactToPost field.
func (r *mutationResolver) ReactToPost(ctx context.Context, postID string, emoji string) (*model.Post, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	id, err := uuid.Parse(postID)
	if err != nil {
		return nil, fmt.Errorf("invalid postId: %w", err)
	}
	can, err := r.Perm.CanOnPost(ctx, identity.EffectiveID, perm.ActionView, id)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	if err := r.Posts.React(ctx, id, identity.EffectiveID, emoji); err != nil {
		return nil, err
	}
	return r.loadPost(ctx, id)
}

// UnreactToPost is the resolver for the unreactToPost field.
func (r *mutationResolver) UnreactToPost(ctx context.Context, postID string, emoji string) (*model.Post, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	id, err := uuid.Parse(postID)
	if err != nil {
		return nil, fmt.Errorf("invalid postId: %w", err)
	}
	if err := r.Posts.Unreact(ctx, id, identity.EffectiveID, emoji); err != nil {
		return nil, err
	}
	return r.loadPost(ctx, id)
}

// MarkPostRead is the resolver for the markPostRead field.
func (r *mutationResolver) MarkPostRead(ctx context.Context, postID string) (*model.Post, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	id, err := uuid.Parse(postID)
	if err != nil {
		return nil, fmt.Errorf("invalid postId: %w", err)
	}
	can, err := r.Perm.CanOnPost(ctx, identity.EffectiveID, perm.ActionView, id)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	if err := r.Posts.MarkRead(ctx, id, identity.EffectiveID); err != nil {
		return nil, err
	}
	return r.loadPost(ctx, id)
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*model.Comment, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	postID, err := uuid.Parse(input.PostID)
	if err != nil {
		return nil, fmt.Errorf("invalid postId: %w", err)
	}
	can, err := r.Perm.CanOnPost(ctx, identity.EffectiveID, perm.ActionContribute, postID)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	var parentPtr *uuid.UUID
	if input.ParentID != nil {
		pid, err := uuid.Parse(*input.ParentID)
		if err != nil {
			return nil, fmt.Errorf("invalid parentId: %w", err)
		}
		parentPtr = &pid
	}
	mentions, err := r.resolveMentionSlugs(ctx, post.ExtractMentionSlugs(input.Body))
	if err != nil {
		return nil, err
	}
	id, err := r.Comments.Create(ctx, comment.CreateInput{
		PostID: postID, ParentID: parentPtr, AuthorID: identity.EffectiveID,
		Body: input.Body, Mentions: mentions,
	})
	if err != nil {
		return nil, err
	}
	if err := r.Audit.Write(ctx, audit.Event{
		Action: "comment.create", TargetType: "comment", TargetID: id,
	}); err != nil {
		return nil, err
	}
	return r.loadComment(ctx, id)
}

// EditComment is the resolver for the editComment field.
func (r *mutationResolver) EditComment(ctx context.Context, commentID string, body string) (*model.Comment, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	id, err := uuid.Parse(commentID)
	if err != nil {
		return nil, fmt.Errorf("invalid commentId: %w", err)
	}
	c, err := r.Comments.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	if c.AuthorID != identity.EffectiveID {
		// Non-author edits require moderator on the parent post.
		can, err := r.Perm.CanOnPost(ctx, identity.EffectiveID, perm.ActionModerate, c.PostID)
		if err != nil {
			return nil, err
		}
		if !can {
			return nil, errPermissionDenied
		}
	}
	if err := r.Comments.Edit(ctx, id, identity.EffectiveID, body); err != nil {
		if errors.Is(err, comment.ErrAlreadyEdited) {
			return r.loadComment(ctx, id)
		}
		return nil, err
	}
	if err := r.Audit.Write(ctx, audit.Event{
		Action: "comment.edit", TargetType: "comment", TargetID: id,
	}); err != nil {
		return nil, err
	}
	return r.loadComment(ctx, id)
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, commentID string) (bool, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return false, err
	}
	id, err := uuid.Parse(commentID)
	if err != nil {
		return false, fmt.Errorf("invalid commentId: %w", err)
	}
	c, err := r.Comments.Get(ctx, id)
	if err != nil {
		return false, err
	}
	if c.AuthorID != identity.EffectiveID {
		can, err := r.Perm.CanOnPost(ctx, identity.EffectiveID, perm.ActionModerate, c.PostID)
		if err != nil {
			return false, err
		}
		if !can {
			return false, errPermissionDenied
		}
	}
	if err := r.Comments.Delete(ctx, id); err != nil {
		return false, err
	}
	return true, r.Audit.Write(ctx, audit.Event{
		Action: "comment.delete", TargetType: "comment", TargetID: id,
	})
}

// ReactToComment is the resolver for the reactToComment field.
func (r *mutationResolver) ReactToComment(ctx context.Context, commentID string, emoji string) (*model.Comment, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	id, err := uuid.Parse(commentID)
	if err != nil {
		return nil, fmt.Errorf("invalid commentId: %w", err)
	}
	c, err := r.Comments.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	can, err := r.Perm.CanOnPost(ctx, identity.EffectiveID, perm.ActionView, c.PostID)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	if err := r.Comments.React(ctx, id, identity.EffectiveID, emoji); err != nil {
		return nil, err
	}
	return r.loadComment(ctx, id)
}

// UnreactToComment is the resolver for the unreactToComment field.
func (r *mutationResolver) UnreactToComment(ctx context.Context, commentID string, emoji string) (*model.Comment, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	id, err := uuid.Parse(commentID)
	if err != nil {
		return nil, fmt.Errorf("invalid commentId: %w", err)
	}
	if err := r.Comments.Unreact(ctx, id, identity.EffectiveID, emoji); err != nil {
		return nil, err
	}
	return r.loadComment(ctx, id)
}

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	in := task.CreateInput{
		CreatorID: identity.EffectiveID,
		Title:     input.Title,
		DueAt:     input.DueAt,
	}
	if input.Description != nil {
		in.Description = *input.Description
	}
	for _, t := range input.Tags {
		tid, err := uuid.Parse(t.TagID)
		if err != nil {
			return nil, fmt.Errorf("invalid tagId: %w", err)
		}
		// Creating a task under a tag requires contribute on the tag.
		can, err := r.Perm.Can(ctx, identity.EffectiveID, perm.ActionContribute, tid)
		if err != nil {
			return nil, err
		}
		if !can {
			return nil, errPermissionDenied
		}
		in.Tags = append(in.Tags, task.TagAttachment{
			TagID:        tid,
			ViewRole:     boolOrTrue(t.ViewRole),
			InteractRole: boolOrTrue(t.InteractRole),
			ModerateRole: boolOrTrue(t.ModerateRole),
		})
	}
	for _, a := range input.Assignees {
		pid, err := uuid.Parse(a)
		if err != nil {
			return nil, fmt.Errorf("invalid assignee: %w", err)
		}
		in.Assignees = append(in.Assignees, pid)
	}
	id, err := r.Tasks.Create(ctx, in)
	if err != nil {
		return nil, err
	}
	if err := r.Audit.Write(ctx, audit.Event{
		Action: "task.create", TargetType: "task", TargetID: id,
	}); err != nil {
		return nil, err
	}
	return r.loadTask(ctx, id)
}

// EditTask is the resolver for the editTask field.
func (r *mutationResolver) EditTask(ctx context.Context, input model.EditTaskInput) (*model.Task, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	tid, err := uuid.Parse(input.TaskID)
	if err != nil {
		return nil, fmt.Errorf("invalid taskId: %w", err)
	}
	t, err := r.Tasks.Get(ctx, tid)
	if err != nil {
		if errors.Is(err, task.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	can, err := r.canTaskAction(ctx, identity.EffectiveID, t, perm.ActionContribute)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	clearDue := false
	if input.ClearDueAt != nil {
		clearDue = *input.ClearDueAt
	}
	if err := r.Tasks.Edit(ctx, tid, input.Title, input.Description, input.DueAt, clearDue); err != nil {
		return nil, err
	}
	if err := r.Audit.Write(ctx, audit.Event{
		Action: "task.edit", TargetType: "task", TargetID: tid,
	}); err != nil {
		return nil, err
	}
	return r.loadTask(ctx, tid)
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, taskID string) (bool, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return false, err
	}
	tid, err := uuid.Parse(taskID)
	if err != nil {
		return false, fmt.Errorf("invalid taskId: %w", err)
	}
	t, err := r.Tasks.Get(ctx, tid)
	if err != nil {
		if errors.Is(err, task.ErrNotFound) {
			return false, nil
		}
		return false, err
	}
	can, err := r.canTaskAction(ctx, identity.EffectiveID, t, perm.ActionModerate)
	if err != nil {
		return false, err
	}
	if !can {
		return false, errPermissionDenied
	}
	if err := r.Tasks.Delete(ctx, tid); err != nil {
		return false, err
	}
	if err := r.Audit.Write(ctx, audit.Event{
		Action: "task.delete", TargetType: "task", TargetID: tid,
	}); err != nil {
		return false, err
	}
	return true, nil
}

// SetTaskStatus is the resolver for the setTaskStatus field.
func (r *mutationResolver) SetTaskStatus(ctx context.Context, taskID string, status model.TaskStatus) (*model.Task, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	tid, err := uuid.Parse(taskID)
	if err != nil {
		return nil, fmt.Errorf("invalid taskId: %w", err)
	}
	t, err := r.Tasks.Get(ctx, tid)
	if err != nil {
		if errors.Is(err, task.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	can, err := r.canTaskAction(ctx, identity.EffectiveID, t, perm.ActionContribute)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	if err := r.Tasks.SetStatus(ctx, tid, mapTaskStatusGQLToDB(status)); err != nil {
		return nil, err
	}
	if err := r.Audit.Write(ctx, audit.Event{
		Action: "task.status", TargetType: "task", TargetID: tid,
	}); err != nil {
		return nil, err
	}
	return r.loadTask(ctx, tid)
}

// AssignTask is the resolver for the assignTask field.
func (r *mutationResolver) AssignTask(ctx context.Context, taskID string, principalID string) (*model.Task, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	tid, err := uuid.Parse(taskID)
	if err != nil {
		return nil, fmt.Errorf("invalid taskId: %w", err)
	}
	pid, err := uuid.Parse(principalID)
	if err != nil {
		return nil, fmt.Errorf("invalid principalId: %w", err)
	}
	t, err := r.Tasks.Get(ctx, tid)
	if err != nil {
		if errors.Is(err, task.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	can, err := r.canTaskAction(ctx, identity.EffectiveID, t, perm.ActionContribute)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	if err := r.Tasks.Assign(ctx, tid, pid, identity.EffectiveID); err != nil {
		return nil, err
	}
	if err := r.Audit.Write(ctx, audit.Event{
		Action: "task.assign", TargetType: "task", TargetID: tid,
	}); err != nil {
		return nil, err
	}
	return r.loadTask(ctx, tid)
}

// UnassignTask is the resolver for the unassignTask field.
func (r *mutationResolver) UnassignTask(ctx context.Context, taskID string, principalID string) (*model.Task, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	tid, err := uuid.Parse(taskID)
	if err != nil {
		return nil, fmt.Errorf("invalid taskId: %w", err)
	}
	pid, err := uuid.Parse(principalID)
	if err != nil {
		return nil, fmt.Errorf("invalid principalId: %w", err)
	}
	t, err := r.Tasks.Get(ctx, tid)
	if err != nil {
		if errors.Is(err, task.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	can, err := r.canTaskAction(ctx, identity.EffectiveID, t, perm.ActionContribute)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	if err := r.Tasks.Unassign(ctx, tid, pid); err != nil {
		return nil, err
	}
	if err := r.Audit.Write(ctx, audit.Event{
		Action: "task.unassign", TargetType: "task", TargetID: tid,
	}); err != nil {
		return nil, err
	}
	return r.loadTask(ctx, tid)
}

// WatchTask is the resolver for the watchTask field.
func (r *mutationResolver) WatchTask(ctx context.Context, taskID string) (*model.Task, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	tid, err := uuid.Parse(taskID)
	if err != nil {
		return nil, fmt.Errorf("invalid taskId: %w", err)
	}
	t, err := r.Tasks.Get(ctx, tid)
	if err != nil {
		if errors.Is(err, task.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	can, err := r.canViewTask(ctx, identity.EffectiveID, t)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	if err := r.Tasks.Watch(ctx, tid, identity.EffectiveID); err != nil {
		return nil, err
	}
	return r.loadTask(ctx, tid)
}

// UnwatchTask is the resolver for the unwatchTask field.
func (r *mutationResolver) UnwatchTask(ctx context.Context, taskID string) (*model.Task, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	tid, err := uuid.Parse(taskID)
	if err != nil {
		return nil, fmt.Errorf("invalid taskId: %w", err)
	}
	if err := r.Tasks.Unwatch(ctx, tid, identity.EffectiveID); err != nil {
		return nil, err
	}
	return r.loadTask(ctx, tid)
}

// PromotePostToTask is the resolver for the promotePostToTask field.
func (r *mutationResolver) PromotePostToTask(ctx context.Context, postID string, title string, dueAt *time.Time, assignees []string) (*model.Task, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	pid, err := uuid.Parse(postID)
	if err != nil {
		return nil, fmt.Errorf("invalid postId: %w", err)
	}
	can, err := r.Perm.CanOnPost(ctx, identity.EffectiveID, perm.ActionContribute, pid)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	in := task.PromoteInput{
		PostID:    &pid,
		CreatorID: identity.EffectiveID,
		Title:     title,
		DueAt:     dueAt,
	}
	for _, a := range assignees {
		aid, err := uuid.Parse(a)
		if err != nil {
			return nil, fmt.Errorf("invalid assignee: %w", err)
		}
		in.Assignees = append(in.Assignees, aid)
	}
	tid, err := r.Tasks.PromotePost(ctx, in)
	if err != nil {
		return nil, err
	}
	if err := r.Audit.Write(ctx, audit.Event{
		Action: "task.promote.post", TargetType: "task", TargetID: tid,
	}); err != nil {
		return nil, err
	}
	return r.loadTask(ctx, tid)
}

// PromoteCommentToTask is the resolver for the promoteCommentToTask field.
func (r *mutationResolver) PromoteCommentToTask(ctx context.Context, commentID string, title string, dueAt *time.Time, assignees []string) (*model.Task, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	cid, err := uuid.Parse(commentID)
	if err != nil {
		return nil, fmt.Errorf("invalid commentId: %w", err)
	}
	c, err := r.Comments.Get(ctx, cid)
	if err != nil {
		if errors.Is(err, comment.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	can, err := r.Perm.CanOnPost(ctx, identity.EffectiveID, perm.ActionContribute, c.PostID)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	in := task.PromoteInput{
		CommentID: &cid,
		CreatorID: identity.EffectiveID,
		Title:     title,
		DueAt:     dueAt,
	}
	for _, a := range assignees {
		aid, err := uuid.Parse(a)
		if err != nil {
			return nil, fmt.Errorf("invalid assignee: %w", err)
		}
		in.Assignees = append(in.Assignees, aid)
	}
	tid, err := r.Tasks.PromoteComment(ctx, in)
	if err != nil {
		return nil, err
	}
	if err := r.Audit.Write(ctx, audit.Event{
		Action: "task.promote.comment", TargetType: "task", TargetID: tid,
	}); err != nil {
		return nil, err
	}
	return r.loadTask(ctx, tid)
}

// MarkNotificationRead is the resolver for the markNotificationRead field.
func (r *mutationResolver) MarkNotificationRead(ctx context.Context, notificationIds []string) (int, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return 0, err
	}
	ids := make([]uuid.UUID, 0, len(notificationIds))
	for _, s := range notificationIds {
		id, err := uuid.Parse(s)
		if err != nil {
			return 0, fmt.Errorf("invalid notificationId: %w", err)
		}
		ids = append(ids, id)
	}
	if err := r.Notifications.MarkRead(ctx, identity.EffectiveID, ids); err != nil {
		return 0, err
	}
	return len(ids), nil
}

// MarkAllNotificationsRead is the resolver for the markAllNotificationsRead field.
func (r *mutationResolver) MarkAllNotificationsRead(ctx context.Context) (int, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return 0, err
	}
	var before int
	if err := r.DB.QueryRow(ctx,
		`SELECT count(*) FROM notifications WHERE recipient_id = $1 AND read_at IS NULL`,
		identity.EffectiveID).Scan(&before); err != nil {
		return 0, err
	}
	if err := r.Notifications.MarkAllRead(ctx, identity.EffectiveID); err != nil {
		return 0, err
	}
	return before, nil
}

// CreateChatRoom is the resolver for the createChatRoom field.
func (r *mutationResolver) CreateChatRoom(ctx context.Context, input model.CreateChatRoomInput) (*model.ChatRoom, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	tagIDs := make([]uuid.UUID, 0, len(input.TagIds))
	for _, s := range input.TagIds {
		tid, err := uuid.Parse(s)
		if err != nil {
			return nil, fmt.Errorf("invalid tagId: %w", err)
		}
		// Creating a chat room under a tag requires contribute on the tag.
		can, err := r.Perm.Can(ctx, identity.EffectiveID, perm.ActionContribute, tid)
		if err != nil {
			return nil, err
		}
		if !can {
			return nil, errPermissionDenied
		}
		tagIDs = append(tagIDs, tid)
	}
	parts := []chat.ParticipantInput{{PrincipalID: identity.EffectiveID, Role: "admin"}}
	for _, s := range input.ParticipantIds {
		pid, err := uuid.Parse(s)
		if err != nil {
			return nil, fmt.Errorf("invalid participantId: %w", err)
		}
		if pid == identity.EffectiveID {
			continue // creator already added as admin
		}
		parts = append(parts, chat.ParticipantInput{PrincipalID: pid, Role: "member"})
	}
	id, err := r.Chat.CreateRoom(ctx, chat.CreateRoomInput{
		Tags:         tagIDs,
		Participants: parts,
	})
	if err != nil {
		return nil, err
	}
	if err := r.Audit.Write(ctx, audit.Event{
		Action: "chatroom.create", TargetType: "chat_room", TargetID: id,
	}); err != nil {
		return nil, err
	}
	return r.loadChatRoom(ctx, id)
}

// AddParticipant is the resolver for the addParticipant field.
func (r *mutationResolver) AddParticipant(ctx context.Context, roomID string, principalID string, role *string) (*model.ChatRoom, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	rid, err := uuid.Parse(roomID)
	if err != nil {
		return nil, fmt.Errorf("invalid roomId: %w", err)
	}
	pid, err := uuid.Parse(principalID)
	if err != nil {
		return nil, fmt.Errorf("invalid principalId: %w", err)
	}
	// Modifying participants requires either being a participant already
	// (members can invite) or moderator-on-tag.
	can, err := r.Perm.CanInRoom(ctx, identity.EffectiveID, rid)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	roleStr := ""
	if role != nil {
		roleStr = *role
	}
	if err := r.Chat.AddParticipant(ctx, rid, pid, roleStr); err != nil {
		return nil, err
	}
	if err := r.Audit.Write(ctx, audit.Event{
		Action: "chatroom.add_participant", TargetType: "chat_room", TargetID: rid,
		Diff: json.RawMessage(fmt.Sprintf(`{"principal_id":"%s","role":%q}`, pid, roleStr)),
	}); err != nil {
		return nil, err
	}
	return r.loadChatRoom(ctx, rid)
}

// RemoveParticipant is the resolver for the removeParticipant field.
func (r *mutationResolver) RemoveParticipant(ctx context.Context, roomID string, principalID string) (*model.ChatRoom, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	rid, err := uuid.Parse(roomID)
	if err != nil {
		return nil, fmt.Errorf("invalid roomId: %w", err)
	}
	pid, err := uuid.Parse(principalID)
	if err != nil {
		return nil, fmt.Errorf("invalid principalId: %w", err)
	}
	// Self-leave is always allowed; otherwise need room access.
	if pid != identity.EffectiveID {
		can, err := r.Perm.CanInRoom(ctx, identity.EffectiveID, rid)
		if err != nil {
			return nil, err
		}
		if !can {
			return nil, errPermissionDenied
		}
	}
	if err := r.Chat.RemoveParticipant(ctx, rid, pid); err != nil {
		return nil, err
	}
	return r.loadChatRoom(ctx, rid)
}

// AddRoomTag is the resolver for the addRoomTag field.
func (r *mutationResolver) AddRoomTag(ctx context.Context, roomID string, tagID string) (*model.ChatRoom, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	rid, err := uuid.Parse(roomID)
	if err != nil {
		return nil, fmt.Errorf("invalid roomId: %w", err)
	}
	tid, err := uuid.Parse(tagID)
	if err != nil {
		return nil, fmt.Errorf("invalid tagId: %w", err)
	}
	can, err := r.Perm.CanInRoom(ctx, identity.EffectiveID, rid)
	if err != nil {
		return nil, err
	}
	canTag, err := r.Perm.Can(ctx, identity.EffectiveID, perm.ActionContribute, tid)
	if err != nil {
		return nil, err
	}
	if !can || !canTag {
		return nil, errPermissionDenied
	}
	if err := r.Chat.AddTag(ctx, rid, tid); err != nil {
		return nil, err
	}
	return r.loadChatRoom(ctx, rid)
}

// RemoveRoomTag is the resolver for the removeRoomTag field.
func (r *mutationResolver) RemoveRoomTag(ctx context.Context, roomID string, tagID string) (*model.ChatRoom, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	rid, err := uuid.Parse(roomID)
	if err != nil {
		return nil, fmt.Errorf("invalid roomId: %w", err)
	}
	tid, err := uuid.Parse(tagID)
	if err != nil {
		return nil, fmt.Errorf("invalid tagId: %w", err)
	}
	can, err := r.Perm.CanInRoom(ctx, identity.EffectiveID, rid)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	if err := r.Chat.RemoveTag(ctx, rid, tid); err != nil {
		return nil, err
	}
	return r.loadChatRoom(ctx, rid)
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, input model.SendMessageInput) (*model.Message, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	rid, err := uuid.Parse(input.RoomID)
	if err != nil {
		return nil, fmt.Errorf("invalid roomId: %w", err)
	}
	can, err := r.Perm.CanInRoom(ctx, identity.EffectiveID, rid)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	var replyTo *uuid.UUID
	if input.ReplyTo != nil {
		rt, err := uuid.Parse(*input.ReplyTo)
		if err != nil {
			return nil, fmt.Errorf("invalid replyTo: %w", err)
		}
		replyTo = &rt
	}
	id, err := r.Chat.SendMessage(ctx, chat.SendInput{
		RoomID: rid, AuthorID: identity.EffectiveID, Body: input.Body, ReplyTo: replyTo,
	})
	if err != nil {
		return nil, err
	}
	return r.loadMessage(ctx, id)
}

// EditMessage is the resolver for the editMessage field.
func (r *mutationResolver) EditMessage(ctx context.Context, messageID string, body string) (*model.Message, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	mid, err := uuid.Parse(messageID)
	if err != nil {
		return nil, fmt.Errorf("invalid messageId: %w", err)
	}
	msg, err := r.Chat.GetMessage(ctx, mid)
	if err != nil {
		return nil, err
	}
	if msg.AuthorID != identity.EffectiveID {
		// Non-author edits aren't supported in M3 — chat is more
		// transient than posts. M5 may add admin overrides.
		return nil, errPermissionDenied
	}
	if err := r.Chat.EditMessage(ctx, mid, identity.EffectiveID, body); err != nil {
		if errors.Is(err, chat.ErrAlreadyEdited) {
			return r.loadMessage(ctx, mid)
		}
		return nil, err
	}
	return r.loadMessage(ctx, mid)
}

// DeleteMessage is the resolver for the deleteMessage field.
func (r *mutationResolver) DeleteMessage(ctx context.Context, messageID string) (bool, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return false, err
	}
	mid, err := uuid.Parse(messageID)
	if err != nil {
		return false, fmt.Errorf("invalid messageId: %w", err)
	}
	msg, err := r.Chat.GetMessage(ctx, mid)
	if err != nil {
		return false, err
	}
	if msg.AuthorID != identity.EffectiveID {
		return false, errPermissionDenied
	}
	if err := r.Chat.DeleteMessage(ctx, mid); err != nil {
		return false, err
	}
	return true, nil
}

// PromoteMessage is the resolver for the promoteMessage field.
func (r *mutationResolver) PromoteMessage(ctx context.Context, messageID string) (*model.Post, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	mid, err := uuid.Parse(messageID)
	if err != nil {
		return nil, fmt.Errorf("invalid messageId: %w", err)
	}
	msg, err := r.Chat.GetMessage(ctx, mid)
	if err != nil {
		return nil, err
	}
	can, err := r.Perm.CanInRoom(ctx, identity.EffectiveID, msg.ChatRoomID)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	postID, err := r.Chat.PromoteMessage(ctx, mid, identity.EffectiveID)
	if err != nil {
		return nil, err
	}
	if err := r.Audit.Write(ctx, audit.Event{
		Action: "message.promote", TargetType: "message", TargetID: mid,
		Diff: json.RawMessage(fmt.Sprintf(`{"post_id":"%s"}`, postID)),
	}); err != nil {
		return nil, err
	}
	return r.loadPost(ctx, postID)
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *model.Post, first *int, after *string) (*model.CommentConnection, error) {
	postID, err := uuid.Parse(obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid post id: %w", err)
	}
	limit := 200
	if first != nil && *first > 0 && *first <= 200 {
		limit = *first
	}
	// after-cursor pagination is accepted as a parameter but not yet
	// applied — comments under a post are bounded and clients fetch all
	// in one shot today. M5 wires actual cursor pagination.
	_ = after
	return r.loadCommentsForPost(ctx, postID, limit)
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	if err := r.DB.Ping(ctx); err != nil {
		return "", err
	}
	return "ok", nil
}

// ServerTime is the resolver for the serverTime field.
func (r *queryResolver) ServerTime(ctx context.Context) (*time.Time, error) {
	var value time.Time
	if err := r.DB.QueryRow(ctx, "SELECT now()").Scan(&value); err != nil {
		return nil, err
	}
	return &value, nil
}

// Viewer is the resolver for the viewer field.
func (r *queryResolver) Viewer(ctx context.Context) (*model.User, error) {
	id := auth.FromContext(ctx)
	if id.IsAnonymous() {
		return nil, nil
	}
	return r.loadUser(ctx, id.EffectiveID)
}

// Tag is the resolver for the tag field.
func (r *queryResolver) Tag(ctx context.Context, id string) (*model.Tag, error) {
	tagID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	return r.loadTag(ctx, tagID)
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	postID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	return r.loadPost(ctx, postID)
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	tid, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	return r.loadTask(ctx, tid)
}

// ChatRoom is the resolver for the chatRoom field.
func (r *queryResolver) ChatRoom(ctx context.Context, id string) (*model.ChatRoom, error) {
	rid, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	return r.loadChatRoom(ctx, rid)
}

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context, first *int, after *string, filter *model.NotificationFilter) (*model.NotificationConnection, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	return r.loadInbox(ctx, identity.EffectiveID, first, filter)
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, query string, kinds []model.SearchKind, first *int) (*model.SearchConnection, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	limit := 25
	if first != nil && *first > 0 && *first <= 100 {
		limit = *first
	}
	dbKinds := make([]search.Kind, 0, len(kinds))
	for _, k := range kinds {
		switch k {
		case model.SearchKindPost:
			dbKinds = append(dbKinds, search.KindPost)
		case model.SearchKindComment:
			dbKinds = append(dbKinds, search.KindComment)
		}
	}
	hits, err := r.Resolver.Search.Search(ctx, identity.EffectiveID, query, dbKinds, limit)
	if err != nil {
		return nil, err
	}
	edges := make([]*model.SearchEdge, 0, len(hits))
	for _, h := range hits {
		var node model.SearchResult
		switch h.Kind {
		case search.KindPost:
			p, err := r.loadPost(ctx, h.ID)
			if err != nil {
				return nil, err
			}
			if p == nil {
				continue
			}
			node = p
		case search.KindComment:
			c, err := r.loadComment(ctx, h.ID)
			if err != nil {
				return nil, err
			}
			if c == nil {
				continue
			}
			node = c
		}
		edges = append(edges, &model.SearchEdge{
			Node:   node,
			Cursor: encodeCursor(cursor{CreatedAt: h.CreatedAt, ID: h.ID}),
			Score:  h.Score,
		})
	}
	pi := &model.PageInfo{}
	if len(edges) > 0 {
		s := edges[0].Cursor
		e := edges[len(edges)-1].Cursor
		pi.StartCursor = &s
		pi.EndCursor = &e
	}
	return &model.SearchConnection{Edges: edges, PageInfo: pi}, nil
}

// SearchTags is the resolver for the searchTags field.
func (r *queryResolver) SearchTags(ctx context.Context, query string, first *int) ([]*model.TagSearchHit, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	limit := 15
	if first != nil && *first > 0 && *first <= 50 {
		limit = *first
	}
	hits, err := r.Resolver.Search.SearchTags(ctx, identity.EffectiveID, query, limit)
	if err != nil {
		return nil, err
	}
	out := make([]*model.TagSearchHit, 0, len(hits))
	for _, h := range hits {
		t, err := r.loadTagShallow(ctx, h.ID)
		if err != nil {
			return nil, err
		}
		if t == nil {
			continue
		}
		out = append(out, &model.TagSearchHit{
			Tag:        t,
			Similarity: h.Similarity,
		})
	}
	return out, nil
}

// MessageAdded is the resolver for the messageAdded field.
func (r *subscriptionResolver) MessageAdded(ctx context.Context, roomID string) (<-chan *model.Message, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	rid, err := uuid.Parse(roomID)
	if err != nil {
		return nil, fmt.Errorf("invalid roomId: %w", err)
	}
	can, err := r.Perm.CanInRoom(ctx, identity.EffectiveID, rid)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	out := make(chan *model.Message, 4)
	sub := r.Realtime.Subscribe("chat.room." + rid.String())
	go func() {
		defer close(out)
		defer sub.Close()
		for {
			select {
			case <-ctx.Done():
				return
			case ev, ok := <-sub.Ch:
				if !ok {
					return
				}
				var p struct {
					MessageID string `json:"message_id"`
				}
				if err := json.Unmarshal(ev.Payload, &p); err != nil || p.MessageID == "" {
					continue
				}
				mid, err := uuid.Parse(p.MessageID)
				if err != nil {
					continue
				}
				// Per architecture: recheck visibility on every event so a
				// viewer who lost access mid-session stops receiving.
				stillCan, err := r.Perm.CanInRoom(ctx, identity.EffectiveID, rid)
				if err != nil || !stillCan {
					continue
				}
				msg, err := r.loadMessage(ctx, mid)
				if err != nil || msg == nil {
					continue
				}
				select {
				case out <- msg:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}

// PostChanged is the resolver for the postChanged field.
func (r *subscriptionResolver) PostChanged(ctx context.Context, tagID string) (<-chan *model.Post, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	tid, err := uuid.Parse(tagID)
	if err != nil {
		return nil, fmt.Errorf("invalid tagId: %w", err)
	}
	can, err := r.Perm.Can(ctx, identity.EffectiveID, perm.ActionView, tid)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	out := make(chan *model.Post, 4)
	sub := r.Realtime.Subscribe("posts.tag." + tid.String())
	go func() {
		defer close(out)
		defer sub.Close()
		for {
			select {
			case <-ctx.Done():
				return
			case ev, ok := <-sub.Ch:
				if !ok {
					return
				}
				var p struct {
					PostID string `json:"post_id"`
				}
				if err := json.Unmarshal(ev.Payload, &p); err != nil || p.PostID == "" {
					continue
				}
				pid, err := uuid.Parse(p.PostID)
				if err != nil {
					continue
				}
				stillCan, err := r.Perm.CanOnPost(ctx, identity.EffectiveID, perm.ActionView, pid)
				if err != nil || !stillCan {
					continue
				}
				post, err := r.loadPost(ctx, pid)
				if err != nil || post == nil {
					continue
				}
				select {
				case out <- post:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}

// TagStructureChanged is the resolver for the tagStructureChanged field.
func (r *subscriptionResolver) TagStructureChanged(ctx context.Context, tagID string) (<-chan *model.TagStructureEvent, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	tid, err := uuid.Parse(tagID)
	if err != nil {
		return nil, fmt.Errorf("invalid tagId: %w", err)
	}
	can, err := r.Perm.Can(ctx, identity.EffectiveID, perm.ActionView, tid)
	if err != nil {
		return nil, err
	}
	if !can {
		return nil, errPermissionDenied
	}
	out := make(chan *model.TagStructureEvent, 4)
	sub := r.Realtime.Subscribe("tag." + tid.String() + ".structure")
	go func() {
		defer close(out)
		defer sub.Close()
		for {
			select {
			case <-ctx.Done():
				return
			case ev, ok := <-sub.Ch:
				if !ok {
					return
				}
				var p struct {
					Kind  string `json:"kind"`
					TagID string `json:"tag_id"`
				}
				if err := json.Unmarshal(ev.Payload, &p); err != nil {
					continue
				}
				if p.TagID == "" {
					p.TagID = tid.String()
				}
				stillCan, _ := r.Perm.Can(ctx, identity.EffectiveID, perm.ActionView, tid)
				if !stillCan {
					continue
				}
				select {
				case out <- &model.TagStructureEvent{TagID: p.TagID, Kind: p.Kind}:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}

// NotificationReceived is the resolver for the notificationReceived field.
func (r *subscriptionResolver) NotificationReceived(ctx context.Context) (<-chan *model.Notification, error) {
	identity, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	out := make(chan *model.Notification, 8)
	sub := r.Realtime.Subscribe("notif." + identity.EffectiveID.String())
	go func() {
		defer close(out)
		defer sub.Close()
		for {
			select {
			case <-ctx.Done():
				return
			case ev, ok := <-sub.Ch:
				if !ok {
					return
				}
				var p struct {
					NotificationID string `json:"notification_id"`
				}
				if err := json.Unmarshal(ev.Payload, &p); err != nil || p.NotificationID == "" {
					continue
				}
				nid, err := uuid.Parse(p.NotificationID)
				if err != nil {
					continue
				}
				row, err := r.Notifications.Get(ctx, nid)
				if err != nil || row == nil {
					continue
				}
				// Defense in depth: only deliver to the rightful recipient
				// even though the topic is keyed on principal id.
				if row.RecipientID != identity.EffectiveID {
					continue
				}
				m, err := r.loadNotification(ctx, row)
				if err != nil || m == nil {
					continue
				}
				select {
				case out <- m:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}

// Posts is the resolver for the posts field.
func (r *tagResolver) Posts(ctx context.Context, obj *model.Tag, first *int, after *string, sort *model.PostSort) (*model.PostConnection, error) {
	identity := auth.FromContext(ctx)
	if identity.IsAnonymous() {
		return emptyPostConnection(), nil
	}
	tagID, err := uuid.Parse(obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid tag id: %w", err)
	}
	limit := 25
	if first != nil && *first > 0 && *first <= 100 {
		limit = *first
	}
	// after-cursor and sort accepted but not applied yet — RECENT-by-
	// created_at is the only ordering. Pagination cursors lift in M5.
	_ = after
	_ = sort
	postRows, err := r.Resolver.Posts.ListByTag(ctx, tagID, limit)
	if err != nil {
		return nil, err
	}
	edges := make([]*model.PostEdge, 0, len(postRows))
	for _, p := range postRows {
		can, err := r.Perm.CanOnPost(ctx, identity.EffectiveID, perm.ActionView, p.ID)
		if err != nil {
			return nil, err
		}
		if !can {
			continue
		}
		mp, err := r.loadPost(ctx, p.ID)
		if err != nil {
			return nil, err
		}
		if mp == nil {
			continue
		}
		edges = append(edges, &model.PostEdge{
			Node:   mp,
			Cursor: encodeCursor(cursor{CreatedAt: p.CreatedAt, ID: p.ID}),
		})
	}
	pi := &model.PageInfo{}
	if len(edges) > 0 {
		s := edges[0].Cursor
		e := edges[len(edges)-1].Cursor
		pi.StartCursor = &s
		pi.EndCursor = &e
	}
	return &model.PostConnection{Edges: edges, PageInfo: pi}, nil
}

// Tasks is the resolver for the tasks field.
func (r *tagResolver) Tasks(ctx context.Context, obj *model.Tag, first *int, after *string, status *model.TaskStatus) (*model.TaskConnection, error) {
	tagID, err := uuid.Parse(obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid tag id: %w", err)
	}
	limit := 25
	if first != nil && *first > 0 && *first <= 100 {
		limit = *first
	}
	_ = after
	var dbStatus *string
	if status != nil {
		s := mapTaskStatusGQLToDB(*status)
		dbStatus = &s
	}
	return r.loadTasksForTag(ctx, tagID, limit, dbStatus)
}

// ChatRoom returns ChatRoomResolver implementation.
func (r *Resolver) ChatRoom() ChatRoomResolver { return &chatRoomResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

// Tag returns TagResolver implementation.
func (r *Resolver) Tag() TagResolver { return &tagResolver{r} }

type chatRoomResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type tagResolver struct{ *Resolver }
