package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"time"
)

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	if err := r.DB.Ping(ctx); err != nil {
		return "", err
	}
	return "ok", nil
}

// ServerTime is the resolver for the serverTime field.
func (r *queryResolver) ServerTime(ctx context.Context) (*time.Time, error) {
	var value time.Time
	if err := r.DB.QueryRow(ctx, "SELECT now()").Scan(&value); err != nil {
		return nil, err
	}
	return &value, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
