targets:
  $default:
    sources:
      - lib/**
      - $package$
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: pulse|lib/graphql/schema.graphql
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: pulse|lib/graphql/schema.graphql
