name: pulse
description: Flutter client for Pulse.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ferry: ^0.16.1
  ferry_flutter: ^0.9.1
  flutter_riverpod: ^3.3.1
  go_router: ^17.2.3
  gql_http_link: ^1.2.0
  flutter_secure_storage: ^10.1.0
  gql_websocket_link: ^2.1.0
  gql_exec: ^1.1.1-alpha+1699813812660
  gql_link: ^1.1.0
  drift: ^2.33.0
  drift_flutter: ^0.3.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.15.0
  ferry_generator: ^0.12.0
  drift_dev: ^2.33.0
  sqlite3_flutter_libs: ^0.6.0+eol

flutter:
  uses-material-design: true
