// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type NotificationSource interface {
	IsNotificationSource()
}

type Principal interface {
	IsPrincipal()
	GetID() string
	GetGlobalURI() string
	GetKind() PrincipalKind
	GetStatus() PrincipalStatus
	GetDisplayName() string
	GetHomeTag() *Tag
}

type SearchResult interface {
	IsSearchResult()
}

type Bot struct {
	ID             string          `json:"id"`
	GlobalURI      string          `json:"globalUri"`
	Kind           PrincipalKind   `json:"kind"`
	Status         PrincipalStatus `json:"status"`
	DisplayName    string          `json:"displayName"`
	HomeTag        *Tag            `json:"homeTag,omitempty"`
	OwnerPrincipal Principal       `json:"ownerPrincipal,omitempty"`
}

func (Bot) IsPrincipal()                    {}
func (this Bot) GetID() string              { return this.ID }
func (this Bot) GetGlobalURI() string       { return this.GlobalURI }
func (this Bot) GetKind() PrincipalKind     { return this.Kind }
func (this Bot) GetStatus() PrincipalStatus { return this.Status }
func (this Bot) GetDisplayName() string     { return this.DisplayName }
func (this Bot) GetHomeTag() *Tag           { return this.HomeTag }

type ChatRoom struct {
	ID           string                 `json:"id"`
	GlobalURI    string                 `json:"globalUri"`
	IsDm         bool                   `json:"isDM"`
	Tags         []*Tag                 `json:"tags"`
	Participants []*ChatRoomParticipant `json:"participants"`
	Messages     *MessageConnection     `json:"messages"`
	CreatedAt    time.Time              `json:"createdAt"`
	ArchivedAt   *time.Time             `json:"archivedAt,omitempty"`
}

type ChatRoomParticipant struct {
	Principal Principal  `json:"principal"`
	Role      string     `json:"role"`
	JoinedAt  time.Time  `json:"joinedAt"`
	LeftAt    *time.Time `json:"leftAt,omitempty"`
}

type Comment struct {
	ID        string             `json:"id"`
	PostID    string             `json:"postId"`
	ParentID  *string            `json:"parentId,omitempty"`
	Depth     int                `json:"depth"`
	Author    Principal          `json:"author"`
	Body      string             `json:"body"`
	Mentions  []Principal        `json:"mentions"`
	Reactions []*ReactionSummary `json:"reactions"`
	CreatedAt time.Time          `json:"createdAt"`
	EditedAt  *time.Time         `json:"editedAt,omitempty"`
	DeletedAt *time.Time         `json:"deletedAt,omitempty"`
}

func (Comment) IsSearchResult() {}

func (Comment) IsNotificationSource() {}

type CommentConnection struct {
	Edges    []*CommentEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type CommentEdge struct {
	Node   *Comment `json:"node"`
	Cursor string   `json:"cursor"`
}

type CreateChatRoomInput struct {
	TagIds         []string `json:"tagIds,omitempty"`
	ParticipantIds []string `json:"participantIds,omitempty"`
}

type CreateCommentInput struct {
	PostID   string  `json:"postId"`
	ParentID *string `json:"parentId,omitempty"`
	Body     string  `json:"body"`
}

type CreatePostInput struct {
	Title string          `json:"title"`
	Body  string          `json:"body"`
	Tags  []*PostTagInput `json:"tags"`
}

type CreateTagInput struct {
	ParentID    string  `json:"parentId"`
	Slug        string  `json:"slug"`
	DisplayName string  `json:"displayName"`
	Defaults    *string `json:"defaults,omitempty"`
}

type CreateTaskInput struct {
	Title       string          `json:"title"`
	Description *string         `json:"description,omitempty"`
	DueAt       *time.Time      `json:"dueAt,omitempty"`
	Tags        []*TaskTagInput `json:"tags,omitempty"`
	Assignees   []string        `json:"assignees,omitempty"`
}

type EditPostInput struct {
	PostID string `json:"postId"`
	Title  string `json:"title"`
	Body   string `json:"body"`
}

type EditTaskInput struct {
	TaskID      string     `json:"taskId"`
	Title       *string    `json:"title,omitempty"`
	Description *string    `json:"description,omitempty"`
	DueAt       *time.Time `json:"dueAt,omitempty"`
	ClearDueAt  *bool      `json:"clearDueAt,omitempty"`
}

type GrantTagInput struct {
	TagID       string           `json:"tagId"`
	PrincipalID string           `json:"principalId"`
	Bundle      PermissionBundle `json:"bundle"`
	Extras      []string         `json:"extras,omitempty"`
	Cascade     *bool            `json:"cascade,omitempty"`
}

type ImpersonationState struct {
	IsImpersonating bool      `json:"isImpersonating"`
	Acting          Principal `json:"acting,omitempty"`
	Effective       Principal `json:"effective,omitempty"`
}

type LoginPayload struct {
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expiresAt"`
	Viewer    *User     `json:"viewer"`
}

type Message struct {
	ID             string     `json:"id"`
	GlobalURI      string     `json:"globalUri"`
	ChatRoom       *ChatRoom  `json:"chatRoom"`
	Author         Principal  `json:"author"`
	Body           string     `json:"body"`
	ReplyTo        *Message   `json:"replyTo,omitempty"`
	CreatedAt      time.Time  `json:"createdAt"`
	EditedAt       *time.Time `json:"editedAt,omitempty"`
	DeletedAt      *time.Time `json:"deletedAt,omitempty"`
	PromotedToPost *Post      `json:"promotedToPost,omitempty"`
}

func (Message) IsNotificationSource() {}

type MessageConnection struct {
	Edges    []*MessageEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type MessageEdge struct {
	Node   *Message `json:"node"`
	Cursor string   `json:"cursor"`
}

type Mutation struct {
}

type Notification struct {
	ID         string              `json:"id"`
	Recipient  Principal           `json:"recipient"`
	Reason     NotificationReason  `json:"reason"`
	Urgency    NotificationUrgency `json:"urgency"`
	SourceType string              `json:"sourceType"`
	SourceID   string              `json:"sourceId"`
	Source     NotificationSource  `json:"source,omitempty"`
	SourceTag  *Tag                `json:"sourceTag,omitempty"`
	ReadAt     *time.Time          `json:"readAt,omitempty"`
	CreatedAt  time.Time           `json:"createdAt"`
}

type NotificationConnection struct {
	Edges       []*NotificationEdge `json:"edges"`
	PageInfo    *PageInfo           `json:"pageInfo"`
	UnreadCount int                 `json:"unreadCount"`
}

type NotificationEdge struct {
	Node   *Notification `json:"node"`
	Cursor string        `json:"cursor"`
}

type NotificationFilter struct {
	UnreadOnly *bool                `json:"unreadOnly,omitempty"`
	Reasons    []NotificationReason `json:"reasons,omitempty"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Post struct {
	ID             string             `json:"id"`
	GlobalURI      string             `json:"globalUri"`
	Title          string             `json:"title"`
	Body           string             `json:"body"`
	Author         Principal          `json:"author"`
	Tags           []*PostTag         `json:"tags"`
	Mentions       []Principal        `json:"mentions"`
	Comments       *CommentConnection `json:"comments"`
	Reactions      []*ReactionSummary `json:"reactions"`
	DecisionStatus *DecisionStatus    `json:"decisionStatus,omitempty"`
	DenyFlag       bool               `json:"denyFlag"`
	MyPermissions  *PostPermissions   `json:"myPermissions"`
	CreatedAt      time.Time          `json:"createdAt"`
	EditedAt       *time.Time         `json:"editedAt,omitempty"`
	DeletedAt      *time.Time         `json:"deletedAt,omitempty"`
	LastReadAt     *time.Time         `json:"lastReadAt,omitempty"`
}

func (Post) IsSearchResult() {}

func (Post) IsNotificationSource() {}

type PostConnection struct {
	Edges    []*PostEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type PostEdge struct {
	Node   *Post  `json:"node"`
	Cursor string `json:"cursor"`
}

type PostPermissions struct {
	Bundle        *PermissionBundle `json:"bundle,omitempty"`
	CanView       bool              `json:"canView"`
	CanContribute bool              `json:"canContribute"`
	CanModerate   bool              `json:"canModerate"`
}

type PostTag struct {
	Tag          *Tag `json:"tag"`
	ViewRole     bool `json:"viewRole"`
	InteractRole bool `json:"interactRole"`
	ModerateRole bool `json:"moderateRole"`
}

type PostTagInput struct {
	TagID        string `json:"tagId"`
	ViewRole     *bool  `json:"viewRole,omitempty"`
	InteractRole *bool  `json:"interactRole,omitempty"`
	ModerateRole *bool  `json:"moderateRole,omitempty"`
}

type Query struct {
}

type ReactionSummary struct {
	Emoji    string `json:"emoji"`
	Count    int    `json:"count"`
	ByViewer bool   `json:"byViewer"`
}

type SearchConnection struct {
	Edges    []*SearchEdge `json:"edges"`
	PageInfo *PageInfo     `json:"pageInfo"`
}

type SearchEdge struct {
	Node   SearchResult `json:"node"`
	Cursor string       `json:"cursor"`
	Score  float64      `json:"score"`
}

type SendMessageInput struct {
	RoomID  string  `json:"roomId"`
	Body    string  `json:"body"`
	ReplyTo *string `json:"replyTo,omitempty"`
}

type SubscribeTagInput struct {
	TagID        string               `json:"tagId"`
	Cascade      *bool                `json:"cascade,omitempty"`
	Urgency      *SubscriptionUrgency `json:"urgency,omitempty"`
	ReasonFilter []string             `json:"reasonFilter,omitempty"`
}

type Subscription struct {
}

type Tag struct {
	ID             string           `json:"id"`
	GlobalURI      string           `json:"globalUri"`
	Slug           string           `json:"slug"`
	DisplayName    string           `json:"displayName"`
	Path           string           `json:"path"`
	RootKind       TagRootKind      `json:"rootKind"`
	Parent         *Tag             `json:"parent,omitempty"`
	Children       []*Tag           `json:"children"`
	Defaults       string           `json:"defaults"`
	ArchivedAt     *time.Time       `json:"archivedAt,omitempty"`
	CreatedAt      time.Time        `json:"createdAt"`
	MyPermissions  *TagPermissions  `json:"myPermissions"`
	MySubscription *TagSubscription `json:"mySubscription,omitempty"`
	Posts          *PostConnection  `json:"posts"`
	Tasks          *TaskConnection  `json:"tasks"`
}

type TagPermissions struct {
	Bundle        *PermissionBundle `json:"bundle,omitempty"`
	Extras        []string          `json:"extras"`
	CanView       bool              `json:"canView"`
	CanContribute bool              `json:"canContribute"`
	CanModerate   bool              `json:"canModerate"`
	CanOwn        bool              `json:"canOwn"`
}

type TagSearchHit struct {
	Tag        *Tag    `json:"tag"`
	Similarity float64 `json:"similarity"`
}

type TagStructureEvent struct {
	TagID string `json:"tagId"`
	Kind  string `json:"kind"`
}

type TagSubscription struct {
	Cascade      bool                `json:"cascade"`
	Urgency      SubscriptionUrgency `json:"urgency"`
	ReasonFilter []string            `json:"reasonFilter"`
}

type Task struct {
	ID            string           `json:"id"`
	GlobalURI     string           `json:"globalUri"`
	Title         string           `json:"title"`
	Description   *string          `json:"description,omitempty"`
	Status        TaskStatus       `json:"status"`
	DueAt         *time.Time       `json:"dueAt,omitempty"`
	Tags          []*TaskTag       `json:"tags"`
	Assignees     []Principal      `json:"assignees"`
	Watchers      []Principal      `json:"watchers"`
	LinkedPost    *Post            `json:"linkedPost,omitempty"`
	LinkedComment *Comment         `json:"linkedComment,omitempty"`
	CreatedBy     Principal        `json:"createdBy"`
	MyPermissions *TaskPermissions `json:"myPermissions"`
	CreatedAt     time.Time        `json:"createdAt"`
	EditedAt      *time.Time       `json:"editedAt,omitempty"`
	DeletedAt     *time.Time       `json:"deletedAt,omitempty"`
}

func (Task) IsNotificationSource() {}

type TaskConnection struct {
	Edges    []*TaskEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type TaskEdge struct {
	Node   *Task  `json:"node"`
	Cursor string `json:"cursor"`
}

type TaskPermissions struct {
	Bundle        *PermissionBundle `json:"bundle,omitempty"`
	CanView       bool              `json:"canView"`
	CanContribute bool              `json:"canContribute"`
	CanModerate   bool              `json:"canModerate"`
}

type TaskTag struct {
	Tag          *Tag `json:"tag"`
	ViewRole     bool `json:"viewRole"`
	InteractRole bool `json:"interactRole"`
	ModerateRole bool `json:"moderateRole"`
}

type TaskTagInput struct {
	TagID        string `json:"tagId"`
	ViewRole     *bool  `json:"viewRole,omitempty"`
	InteractRole *bool  `json:"interactRole,omitempty"`
	ModerateRole *bool  `json:"moderateRole,omitempty"`
}

type User struct {
	ID          string          `json:"id"`
	GlobalURI   string          `json:"globalUri"`
	Kind        PrincipalKind   `json:"kind"`
	Status      PrincipalStatus `json:"status"`
	DisplayName string          `json:"displayName"`
	HomeTag     *Tag            `json:"homeTag,omitempty"`
	Email       *string         `json:"email,omitempty"`
}

func (User) IsPrincipal()                    {}
func (this User) GetID() string              { return this.ID }
func (this User) GetGlobalURI() string       { return this.GlobalURI }
func (this User) GetKind() PrincipalKind     { return this.Kind }
func (this User) GetStatus() PrincipalStatus { return this.Status }
func (this User) GetDisplayName() string     { return this.DisplayName }
func (this User) GetHomeTag() *Tag           { return this.HomeTag }

type DecisionStatus string

const (
	DecisionStatusDecision DecisionStatus = "DECISION"
	DecisionStatusAnswer   DecisionStatus = "ANSWER"
)

var AllDecisionStatus = []DecisionStatus{
	DecisionStatusDecision,
	DecisionStatusAnswer,
}

func (e DecisionStatus) IsValid() bool {
	switch e {
	case DecisionStatusDecision, DecisionStatusAnswer:
		return true
	}
	return false
}

func (e DecisionStatus) String() string {
	return string(e)
}

func (e *DecisionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DecisionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DecisionStatus", str)
	}
	return nil
}

func (e DecisionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DecisionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DecisionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DevicePlatform string

const (
	DevicePlatformIos     DevicePlatform = "IOS"
	DevicePlatformAndroid DevicePlatform = "ANDROID"
	DevicePlatformWeb     DevicePlatform = "WEB"
)

var AllDevicePlatform = []DevicePlatform{
	DevicePlatformIos,
	DevicePlatformAndroid,
	DevicePlatformWeb,
}

func (e DevicePlatform) IsValid() bool {
	switch e {
	case DevicePlatformIos, DevicePlatformAndroid, DevicePlatformWeb:
		return true
	}
	return false
}

func (e DevicePlatform) String() string {
	return string(e)
}

func (e *DevicePlatform) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DevicePlatform(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DevicePlatform", str)
	}
	return nil
}

func (e DevicePlatform) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DevicePlatform) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DevicePlatform) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type NotificationReason string

const (
	NotificationReasonAssignment      NotificationReason = "ASSIGNMENT"
	NotificationReasonMention         NotificationReason = "MENTION"
	NotificationReasonWatcher         NotificationReason = "WATCHER"
	NotificationReasonTagSubscription NotificationReason = "TAG_SUBSCRIPTION"
	NotificationReasonDm              NotificationReason = "DM"
)

var AllNotificationReason = []NotificationReason{
	NotificationReasonAssignment,
	NotificationReasonMention,
	NotificationReasonWatcher,
	NotificationReasonTagSubscription,
	NotificationReasonDm,
}

func (e NotificationReason) IsValid() bool {
	switch e {
	case NotificationReasonAssignment, NotificationReasonMention, NotificationReasonWatcher, NotificationReasonTagSubscription, NotificationReasonDm:
		return true
	}
	return false
}

func (e NotificationReason) String() string {
	return string(e)
}

func (e *NotificationReason) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NotificationReason(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NotificationReason", str)
	}
	return nil
}

func (e NotificationReason) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NotificationReason) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NotificationReason) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type NotificationUrgency string

const (
	NotificationUrgencyHigh   NotificationUrgency = "HIGH"
	NotificationUrgencyNormal NotificationUrgency = "NORMAL"
	NotificationUrgencyLow    NotificationUrgency = "LOW"
)

var AllNotificationUrgency = []NotificationUrgency{
	NotificationUrgencyHigh,
	NotificationUrgencyNormal,
	NotificationUrgencyLow,
}

func (e NotificationUrgency) IsValid() bool {
	switch e {
	case NotificationUrgencyHigh, NotificationUrgencyNormal, NotificationUrgencyLow:
		return true
	}
	return false
}

func (e NotificationUrgency) String() string {
	return string(e)
}

func (e *NotificationUrgency) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NotificationUrgency(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NotificationUrgency", str)
	}
	return nil
}

func (e NotificationUrgency) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NotificationUrgency) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NotificationUrgency) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PermissionBundle string

const (
	PermissionBundleViewer      PermissionBundle = "VIEWER"
	PermissionBundleContributor PermissionBundle = "CONTRIBUTOR"
	PermissionBundleModerator   PermissionBundle = "MODERATOR"
	PermissionBundleOwner       PermissionBundle = "OWNER"
)

var AllPermissionBundle = []PermissionBundle{
	PermissionBundleViewer,
	PermissionBundleContributor,
	PermissionBundleModerator,
	PermissionBundleOwner,
}

func (e PermissionBundle) IsValid() bool {
	switch e {
	case PermissionBundleViewer, PermissionBundleContributor, PermissionBundleModerator, PermissionBundleOwner:
		return true
	}
	return false
}

func (e PermissionBundle) String() string {
	return string(e)
}

func (e *PermissionBundle) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PermissionBundle(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PermissionBundle", str)
	}
	return nil
}

func (e PermissionBundle) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PermissionBundle) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PermissionBundle) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PostSort string

const (
	PostSortRecent PostSort = "RECENT"
	PostSortActive PostSort = "ACTIVE"
)

var AllPostSort = []PostSort{
	PostSortRecent,
	PostSortActive,
}

func (e PostSort) IsValid() bool {
	switch e {
	case PostSortRecent, PostSortActive:
		return true
	}
	return false
}

func (e PostSort) String() string {
	return string(e)
}

func (e *PostSort) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PostSort(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PostSort", str)
	}
	return nil
}

func (e PostSort) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PostSort) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PostSort) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PrincipalKind string

const (
	PrincipalKindUser PrincipalKind = "USER"
	PrincipalKindBot  PrincipalKind = "BOT"
)

var AllPrincipalKind = []PrincipalKind{
	PrincipalKindUser,
	PrincipalKindBot,
}

func (e PrincipalKind) IsValid() bool {
	switch e {
	case PrincipalKindUser, PrincipalKindBot:
		return true
	}
	return false
}

func (e PrincipalKind) String() string {
	return string(e)
}

func (e *PrincipalKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PrincipalKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PrincipalKind", str)
	}
	return nil
}

func (e PrincipalKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PrincipalKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PrincipalKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PrincipalStatus string

const (
	PrincipalStatusActive     PrincipalStatus = "ACTIVE"
	PrincipalStatusTombstoned PrincipalStatus = "TOMBSTONED"
)

var AllPrincipalStatus = []PrincipalStatus{
	PrincipalStatusActive,
	PrincipalStatusTombstoned,
}

func (e PrincipalStatus) IsValid() bool {
	switch e {
	case PrincipalStatusActive, PrincipalStatusTombstoned:
		return true
	}
	return false
}

func (e PrincipalStatus) String() string {
	return string(e)
}

func (e *PrincipalStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PrincipalStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PrincipalStatus", str)
	}
	return nil
}

func (e PrincipalStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PrincipalStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PrincipalStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SearchKind string

const (
	SearchKindPost    SearchKind = "POST"
	SearchKindComment SearchKind = "COMMENT"
	SearchKindTask    SearchKind = "TASK"
	SearchKindMessage SearchKind = "MESSAGE"
)

var AllSearchKind = []SearchKind{
	SearchKindPost,
	SearchKindComment,
	SearchKindTask,
	SearchKindMessage,
}

func (e SearchKind) IsValid() bool {
	switch e {
	case SearchKindPost, SearchKindComment, SearchKindTask, SearchKindMessage:
		return true
	}
	return false
}

func (e SearchKind) String() string {
	return string(e)
}

func (e *SearchKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SearchKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SearchKind", str)
	}
	return nil
}

func (e SearchKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SearchKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SearchKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SubscriptionUrgency string

const (
	SubscriptionUrgencyHigh   SubscriptionUrgency = "HIGH"
	SubscriptionUrgencyNormal SubscriptionUrgency = "NORMAL"
	SubscriptionUrgencyLow    SubscriptionUrgency = "LOW"
	SubscriptionUrgencyMute   SubscriptionUrgency = "MUTE"
)

var AllSubscriptionUrgency = []SubscriptionUrgency{
	SubscriptionUrgencyHigh,
	SubscriptionUrgencyNormal,
	SubscriptionUrgencyLow,
	SubscriptionUrgencyMute,
}

func (e SubscriptionUrgency) IsValid() bool {
	switch e {
	case SubscriptionUrgencyHigh, SubscriptionUrgencyNormal, SubscriptionUrgencyLow, SubscriptionUrgencyMute:
		return true
	}
	return false
}

func (e SubscriptionUrgency) String() string {
	return string(e)
}

func (e *SubscriptionUrgency) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SubscriptionUrgency(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SubscriptionUrgency", str)
	}
	return nil
}

func (e SubscriptionUrgency) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SubscriptionUrgency) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SubscriptionUrgency) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TagRootKind string

const (
	TagRootKindOrg  TagRootKind = "ORG"
	TagRootKindUser TagRootKind = "USER"
)

var AllTagRootKind = []TagRootKind{
	TagRootKindOrg,
	TagRootKindUser,
}

func (e TagRootKind) IsValid() bool {
	switch e {
	case TagRootKindOrg, TagRootKindUser:
		return true
	}
	return false
}

func (e TagRootKind) String() string {
	return string(e)
}

func (e *TagRootKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TagRootKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TagRootKind", str)
	}
	return nil
}

func (e TagRootKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TagRootKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TagRootKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskStatus string

const (
	TaskStatusOpen       TaskStatus = "OPEN"
	TaskStatusInProgress TaskStatus = "IN_PROGRESS"
	TaskStatusBlocked    TaskStatus = "BLOCKED"
	TaskStatusDone       TaskStatus = "DONE"
	TaskStatusCancelled  TaskStatus = "CANCELLED"
)

var AllTaskStatus = []TaskStatus{
	TaskStatusOpen,
	TaskStatusInProgress,
	TaskStatusBlocked,
	TaskStatusDone,
	TaskStatusCancelled,
}

func (e TaskStatus) IsValid() bool {
	switch e {
	case TaskStatusOpen, TaskStatusInProgress, TaskStatusBlocked, TaskStatusDone, TaskStatusCancelled:
		return true
	}
	return false
}

func (e TaskStatus) String() string {
	return string(e)
}

func (e *TaskStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskStatus", str)
	}
	return nil
}

func (e TaskStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
